local o = vim.opt

o.compatible = false
o.showmatch = true
o.ignorecase = true
o.hlsearch = true
o.incsearch = true
o.tabstop = 4
o.softtabstop = 4
o.shiftwidth = 4
o.autoindent = true
o.autoindent = true
o.number = true
o.clipboard = unnamedplus
o.ttyfast = true
o.swapfile = false
o.cursorline = true
o.termguicolors = true
o.wrap = false
